# Placeholder — replace inside the installer with the file generated by
# `nixos-generate-config --root /mnt`, which embeds disk UUIDs and the
# kernel modules specific to this machine. See README for the clone-and-
# install sequence.
{ }
